# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile.rb, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_protocolable}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Igor Alexandrov"]
  s.date = %q{2010-07-21}
  s.description = %q{ActsAsProtocolable is the easiest way to protocol user activity inside your Rails admin interface.}
  s.email = %q{igor.alexandrov@gmail.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "README.textile",
     "Rakefile.rb",
     "VERSION",
     "generators/acts_as_protocolable_migration/acts_as_protocolable_migration_generator.rb",
     "generators/acts_as_protocolable_migration/templates/migration.rb",
     "lib/acts_as_protocolable.rb",
     "lib/acts_as_protocolable/base.rb",
     "lib/acts_as_protocolable/for_model.rb",
     "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/igor-alexandrov/acts_as_protocolable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Guard of activity in your rails application.}
  s.test_files = [
    "test/test_acts_as_protocolable.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sys-admin>, [">= 1.5.2"])
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3.0"])
    else
      s.add_dependency(%q<sys-admin>, [">= 1.5.2"])
      s.add_dependency(%q<activerecord>, [">= 2.3.0"])
    end
  else
    s.add_dependency(%q<sys-admin>, [">= 1.5.2"])
    s.add_dependency(%q<activerecord>, [">= 2.3.0"])
  end
end

